task:
  name: Build
  macos_instance:
    image: sequoia-codeql
  codeql_script: OS_TYPE="${OS_TYPE}" OS_VERSION="${OS_VERSION}" bash -x codeql.sh
  timeout_in: 420m  # 7 hours
  binary_artifacts:
    path: webkit*.zip
