task:
  name: Build
  macos_instance:
    image: sequoia-codeql
  codeql_script: OS_TYPE="${OS_TYPE}" OS_VERSION="${OS_VERSION}" CODEQL_RAM="--ram=32768" bash -x codeql.sh --jsc
  timeout_in: 420m  # 7 hours
  binary_artifacts:
    path: jsc-*.zip
