name: WebKit CodeQL

on:
  push:
    branches: [ main ]
    paths-ignore: [ "*.md" ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        ios-version: [ '18.3.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deps
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build WebKit CodeQL Database
        run: |
          OS_TYPE="iOS" IOS_VERSION='${{ matrix.ios-version }}' bash -x codeql.sh
          echo "$(shasum -a 256 webkit-codeql.zip)"
          shasum -a 256 webkit-codeql.zip > webkit-codeql.zip.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webkit-codeql-${{ matrix.ios-version }}
          path: webkit-codeql.zip

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ls -lah
          gh release upload v${{ matrix.ios-version }} --clobber webkit_compile_commands.zip
          gh release upload v${{ matrix.ios-version }} --clobber webkit-codeql.zip
          gh release upload v${{ matrix.ios-version }} --clobber webkit-codeql.zip.sha256